$ANSIBLE_VAULT;1.1;AES256
61346162666439313466343061643036373437633834376565313734663338336134383833366238
3639333863333766396264383837623363343063633830620a633337373035653431316130323036
30323131343536393031373633383530386637366234363537376262303638653335373030393633
3461313962363865320a376135653862323636313031663736336466636333323731303331646439
36323230613335363262323031633137316534303337616333363831666562323832613335326136
32653963373063303266363534336563353537333262373732323365333831643866383230386135
31643665643935373566626635313061303631323366643236376565303162323866323636346230
65363339626563626562646138316630636266396634373532343636643935616331343834653165
31363932336431626636643534323666653035336565653161663139613864306630333161623338
32333336353735666266313165613939353561326634613737336239653765306561613231323736
64666132616466356461663965356433653835326438613532623666396135346231646438656133
63393364393938313332366432346436396365393430363735383035613235313862653930616566
61666536323238316233643063663835353430666266393432366263646633663233663538393835
38643339376134383238613830323762343336613762393162333334653433613533613561356631
31613733333234653662633264653637386631666237346166353864613335396335363935623936
66623763356238656136
