docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
docker_user: "ubuntu"
docker_gpg_url: "https://download.docker.com/linux/ubuntu/gpg"
docker_repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"